server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://192.168.60.130:3306/test
    username: root
    password: 123456
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      generate_statistics: true
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org:
      hibernate:
        stat: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true