server:
  port: 8011


spring:
  datasource:
    url: jdbc:mysql://192.168.61.130:3306/test
    username: root
    password: 123456
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      generate_statistics: true
    open-in-view: true
  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    com:
      zaxxer:
        hikari: trace
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: trace
      hibernate:
        engine:
          transaction:
            internal: trace
        internal: trace
        stat: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    db:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true