server:
  port: 8011

spring:
  datasource:
    url: jdbc:mysql://192.168.61.130:3306/test
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace