server:
  port: 8011

spring:
#  datasource:
#    url: jdbc:mysql://192.168.61.130:3306/test
#    username: root
#    password: 123456
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace